import type { Metadata } from 'next'
import { Teko } from 'next/font/google'
import Navbar from './components/Navbar/Navbar.jsx'
import './globals.css'
import { ReduxProviders } from './Redux/provider' 
import Tab from './components/Tab/tab'

const teko = Teko({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'EduBudy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={teko.className}>
      <body >
        
          <ReduxProviders>
            <Navbar />
            <Tab />
            {children}
          </ReduxProviders>

        </body>
    </html>
  )
}
